services:
  - type: web
    name: yamama-warehouse-ai-agent
    runtime: python3
    buildCommand: pip install --upgrade pip && pip install flask gunicorn python-dotenv requests
    startCommand: gunicorn --bind 0.0.0.0:$PORT simple_app:app --timeout 60 --workers 1 --max-requests 500
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "1"
      - key: MAX_WORKERS
        value: "1"
