services:
  - type: web
    name: yamama-cement-final
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: API_URL
        value: https://yamama-cement-final.onrender.com
      - key: BASE_URL
        value: https://yamama-cement-final.onrender.com
      - key: YAMAMA_AI_API_URL
        value: https://yamama-cement-final.onrender.com
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: GOOGLE_API_KEY
        value: AIzaSyASSS8H6lPc6P6dd6hBtVHhOXCWZV2qxKA
